/* Generated by Cython 0.29.25 */

#ifndef __PYX_HAVE__pythonabout
#define __PYX_HAVE__pythonabout

#include "Python.h"

#ifndef __PYX_HAVE_API__pythonabout

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *get_python_version(void);

#endif /* !__PYX_HAVE_API__pythonabout */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyObject* initpythonabout(void);
#else
PyObject* PyInit_pythonabout(void);
#endif

#endif /* !__PYX_HAVE__pythonabout */
